from enum import Enum

from charlie_pinboard.domain.errors import DecisionFailureCode


class ActionQueryError(RuntimeError):
    code: DecisionFailureCode

    def __init__(self, code: DecisionFailureCode, message: str) -> None:
        self.code = code
        super().__init__(f"{code.value}: {message}")


class QueryErrorCode(Enum):
    PARALLEL_SELECTION_INVALID = "PARALLEL_SELECTION_INVALID"
    PARALLEL_TIME_INVALID = "PARALLEL_TIME_INVALID"
    WORK_STATE_INVALID = "WORK_STATE_INVALID"


class QueryError(RuntimeError):
    code: QueryErrorCode

    def __init__(self, code: QueryErrorCode, message: str) -> None:
        self.code = code
        super().__init__(f"{code.value}: {message}")


class DispatchErrorCode(Enum):
    COORDINATION_LEASE_REQUIRED = "COORDINATION_LEASE_REQUIRED"
    DISPATCH_ACTION_INVALID = "DISPATCH_ACTION_INVALID"
    DISPATCH_ACTION_UNAVAILABLE = "DISPATCH_ACTION_UNAVAILABLE"
    DISPATCH_ARCHITECTURE_IMPACT_INVALID = "DISPATCH_ARCHITECTURE_IMPACT_INVALID"
    DISPATCH_ATTEMPT_NOT_ACTIVE = "DISPATCH_ATTEMPT_NOT_ACTIVE"
    DISPATCH_AUTHORITY_COVERAGE_INVALID = "DISPATCH_AUTHORITY_COVERAGE_INVALID"
    DISPATCH_AUTHORITY_COVERAGE_MISSING = "DISPATCH_AUTHORITY_COVERAGE_MISSING"
    DISPATCH_AUTHORITY_SELECTOR_INVALID = "DISPATCH_AUTHORITY_SELECTOR_INVALID"
    DISPATCH_AUTHORITY_STALE = "DISPATCH_AUTHORITY_STALE"
    DISPATCH_AUTHORITY_UNREADABLE = "DISPATCH_AUTHORITY_UNREADABLE"
    DISPATCH_BOUNDARY_INVALID = "DISPATCH_BOUNDARY_INVALID"
    DISPATCH_BOUNDARY_MISSING = "DISPATCH_BOUNDARY_MISSING"
    DISPATCH_BRANCH_MISMATCH = "DISPATCH_BRANCH_MISMATCH"
    DISPATCH_BRIEF_INVALID = "DISPATCH_BRIEF_INVALID"
    DISPATCH_BRIEF_MISSING = "DISPATCH_BRIEF_MISSING"
    DISPATCH_BRIEF_REVIEW_ARGUMENT_INVALID = "DISPATCH_BRIEF_REVIEW_ARGUMENT_INVALID"
    DISPATCH_BRIEF_REVIEW_COLLISION = "DISPATCH_BRIEF_REVIEW_COLLISION"
    DISPATCH_BRIEF_REVIEW_INCOMPLETE = "DISPATCH_BRIEF_REVIEW_INCOMPLETE"
    DISPATCH_BRIEF_REVIEW_INVALID = "DISPATCH_BRIEF_REVIEW_INVALID"
    DISPATCH_BRIEF_REVIEW_MISSING = "DISPATCH_BRIEF_REVIEW_MISSING"
    DISPATCH_BRIEF_REVIEW_NOT_INDEPENDENT = "DISPATCH_BRIEF_REVIEW_NOT_INDEPENDENT"
    DISPATCH_BRIEF_REVIEW_NOT_READY = "DISPATCH_BRIEF_REVIEW_NOT_READY"
    DISPATCH_BRIEF_REVIEW_STALE = "DISPATCH_BRIEF_REVIEW_STALE"
    DISPATCH_CHECKOUT_MISSING = "DISPATCH_CHECKOUT_MISSING"
    DISPATCH_CHECKPOINT_AMBIGUOUS = "DISPATCH_CHECKPOINT_AMBIGUOUS"
    DISPATCH_CHECKPOINT_MISSING = "DISPATCH_CHECKPOINT_MISSING"
    DISPATCH_CHECKPOINT_NOT_BUILDABLE = "DISPATCH_CHECKPOINT_NOT_BUILDABLE"
    DISPATCH_CONTRACT_INCOMPLETE = "DISPATCH_CONTRACT_INCOMPLETE"
    DISPATCH_CONTRACT_INVALID = "DISPATCH_CONTRACT_INVALID"
    DISPATCH_CONTRACT_MISSING = "DISPATCH_CONTRACT_MISSING"
    DISPATCH_ENVIRONMENT_INVALID = "DISPATCH_ENVIRONMENT_INVALID"
    DISPATCH_ENVIRONMENT_UNREADABLE = "DISPATCH_ENVIRONMENT_UNREADABLE"
    DISPATCH_LIFECYCLE_PARTITION_INVALID = "DISPATCH_LIFECYCLE_PARTITION_INVALID"
    DISPATCH_PROMPT_NOT_CANONICAL = "DISPATCH_PROMPT_NOT_CANONICAL"
    DISPATCH_PROMPT_UNREADABLE = "DISPATCH_PROMPT_UNREADABLE"
    DISPATCH_REVIEWED_AUTHORITIES_INVALID = "DISPATCH_REVIEWED_AUTHORITIES_INVALID"
    DISPATCH_REVIEWED_AUTHORITIES_MISSING = "DISPATCH_REVIEWED_AUTHORITIES_MISSING"
    STALE_ACTION = "STALE_ACTION"


class DispatchError(RuntimeError):
    code: DispatchErrorCode

    def __init__(self, code: DispatchErrorCode, message: str) -> None:
        self.code = code
        super().__init__(f"{code.value}: {message}")


class PortableCopyErrorCode(Enum):
    PORTABLE_COPY_DESTINATION_EXISTS = "PORTABLE_COPY_DESTINATION_EXISTS"
    PORTABLE_COPY_DESTINATION_INVALID = "PORTABLE_COPY_DESTINATION_INVALID"
    PORTABLE_COPY_SOURCE_NOT_QUIESCENT = "PORTABLE_COPY_SOURCE_NOT_QUIESCENT"
    STORAGE_INVARIANT_VIOLATION = "STORAGE_INVARIANT_VIOLATION"
    STORAGE_IO_ERROR = "STORAGE_IO_ERROR"
    WORK_STATE_INVALID = "WORK_STATE_INVALID"


class PortableCopyError(RuntimeError):
    code: PortableCopyErrorCode

    def __init__(self, code: PortableCopyErrorCode, message: str) -> None:
        self.code = code
        super().__init__(f"{code.value}: {message}")


class MutationContractErrorCode(Enum):
    ACCEPTED_PROPOSAL_INCOMPLETE = "MUTATION_ACCEPTED_PROPOSAL_INCOMPLETE"
    ATTEMPT_AUTHORITY_COUNTER_MISSING = "MUTATION_ATTEMPT_AUTHORITY_COUNTER_MISSING"
    ATTEMPT_AUTHORITY_COUNTER_STALE = "MUTATION_ATTEMPT_AUTHORITY_COUNTER_STALE"
    ATTEMPT_AUTHORITY_GENERATION_INVALID = "MUTATION_ATTEMPT_AUTHORITY_GENERATION_INVALID"
    ATTEMPT_AUTHORITY_GENERATION_MISSING = "MUTATION_ATTEMPT_AUTHORITY_GENERATION_MISSING"
    ATTEMPT_AUTHORITY_LEASE_MISSING = "MUTATION_ATTEMPT_AUTHORITY_LEASE_MISSING"
    ATTEMPT_CHANGE_INCOMPLETE = "MUTATION_ATTEMPT_CHANGE_INCOMPLETE"
    ATTEMPT_CREATION_INCOMPLETE = "MUTATION_ATTEMPT_CREATION_INCOMPLETE"
    ATTEMPT_ITEM_MISSING = "MUTATION_ATTEMPT_ITEM_MISSING"
    COORDINATION_CARRIER_INVALID = "MUTATION_COORDINATION_CARRIER_INVALID"
    COORDINATION_DECISION_MISMATCH = "MUTATION_COORDINATION_DECISION_MISMATCH"
    COORDINATION_EXPECTED_ABSENT = "MUTATION_COORDINATION_EXPECTED_ABSENT"
    COORDINATION_STALE = "MUTATION_COORDINATION_STALE"
    ITEM_CHANGE_STALE = "MUTATION_ITEM_CHANGE_STALE"
    PROPOSAL_CHANGE_STALE = "MUTATION_PROPOSAL_CHANGE_STALE"
    PROPOSAL_EXISTS = "MUTATION_PROPOSAL_EXISTS"
    RECEIPT_MISMATCH = "MUTATION_RECEIPT_MISMATCH"
    REVIEW_PROVENANCE_MISSING = "MUTATION_REVIEW_PROVENANCE_MISSING"
    TERMINAL_STATE_INVALID = "MUTATION_TERMINAL_STATE_INVALID"
    TRANSFER_STALE = "MUTATION_TRANSFER_STALE"


class MutationContractError(ValueError):
    code: MutationContractErrorCode

    def __init__(self, code: MutationContractErrorCode, message: str) -> None:
        self.code = code
        super().__init__(f"{code.value}: {message}")
