import tempfile
import unittest
from pathlib import Path

from docs.how_it_works import render
from docs.how_it_works.model import Box, Connector, Diagram, render_svg

ROOT = Path(__file__).resolve().parent.parent


class HowItWorksDocumentationTests(unittest.TestCase):
    def test_source_model_builds_the_complete_visitor_guide(self) -> None:
        outputs = render.build_outputs(ROOT)

        self.assertEqual(
            {
                Path("HOW_IT_WORKS.md"),
                Path("assets/how-it-works/product.svg"),
                Path("assets/how-it-works/layers.svg"),
                Path("assets/how-it-works/journey.svg"),
                Path("assets/how-it-works/database.svg"),
            },
            outputs.keys(),
        )
        guide = outputs[Path("HOW_IT_WORKS.md")]
        self.assertIn("<!-- Generated by docs.how_it_works", guide)
        self.assertIn("## What moves", guide)
        self.assertIn("## What each transition preserves", guide)
        self.assertIn("## Where responsibilities live", guide)
        self.assertIn("## Follow one change", guide)
        self.assertIn("## The durable memory underneath", guide)

    def test_diagrams_use_the_approved_reading_surface(self) -> None:
        outputs = render.build_outputs(ROOT)

        for path, svg in outputs.items():
            if path.suffix != ".svg":
                continue
            with self.subTest(path=path):
                self.assertIn('fill="#fffdf7"', svg)
                self.assertIn('<pattern id="grid"', svg)
                self.assertIn("stroke: #697487", svg)
                self.assertIn('fill="#394a62"', svg)
                self.assertNotIn("linearGradient", svg)
                self.assertNotIn("feDropShadow", svg)

    def test_renderer_rejects_fragile_connector_geometry(self) -> None:
        boxes = (
            Box("source", "", "Source", (), (), 10, 10, 100, 60),
            Box("target", "", "Target", (), (), 160, 10, 100, 60),
        )
        unsafe_routes = (
            (Connector(((110, 10), (160, 10)), "source", "target"), "stable card port"),
            (Connector(((110, 40), (160, 60)), "source", "target"), "orthogonal"),
        )

        for connector, message in unsafe_routes:
            with self.subTest(message=message), self.assertRaisesRegex(ValueError, message):
                render_svg(
                    Diagram("unsafe", "Unsafe", "Unsafe route", 280, 100, (), (), (connector,), boxes),
                    "source-revision",
                )

    def test_write_and_stale_check_round_trip(self) -> None:
        outputs = render.build_outputs(ROOT)
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory)
            render.write_outputs(destination, outputs)
            self.assertEqual((), render.stale_outputs(destination, outputs))

            changed = destination / "HOW_IT_WORKS.md"
            changed.write_text("stale\n", encoding="utf-8")
            self.assertEqual((Path("HOW_IT_WORKS.md"),), render.stale_outputs(destination, outputs))

    def test_committed_outputs_match_their_sources(self) -> None:
        outputs = render.build_outputs(ROOT)

        self.assertEqual((), render.stale_outputs(ROOT, outputs))

    def test_public_and_agent_facing_prose_uses_the_product_name(self) -> None:
        prose_paths = {ROOT / name for name in ("README.md", "HOW_IT_WORKS.md", "ARCHITECTURE.md")}
        prose_paths.update(path for path in (ROOT / "docs").rglob("*.md") if path.name != "AGENTS.md")
        prose_paths.update((ROOT / "skills").rglob("*.md"))

        for path in sorted(prose_paths):
            with self.subTest(path=path.relative_to(ROOT)):
                prose = path.read_text(encoding="utf-8")
                self.assertNotRegex(prose, r"\bCharlie\b(?!'s pinboard)")


if __name__ == "__main__":
    unittest.main()
