import re
import shutil
import tempfile
import tomllib
import unittest
from dataclasses import astuple, replace
from pathlib import Path
from unittest.mock import patch
from xml.etree import ElementTree

from docs.how_it_works import database, handover, journey, layers, product, render
from docs.how_it_works.model import DAY_PALETTE, NIGHT_PALETTE, Box, Connector, Diagram, Palette, render_svg

from pinboard.domain import decision_models

ROOT = Path(__file__).resolve().parent.parent


class HowItWorksDocumentationTests(unittest.TestCase):
    def test_source_model_builds_the_complete_visitor_guide(self) -> None:
        outputs = render.build_outputs(ROOT)

        self.assertEqual(
            {
                Path("HOW_IT_WORKS.md"),
                Path("assets/how-it-works/product.svg"),
                Path("assets/how-it-works/layers.svg"),
                Path("assets/how-it-works/journey.svg"),
                Path("assets/how-it-works/database.svg"),
                Path("assets/how-it-works/handover.svg"),
                Path("assets/how-it-works/product-dark.svg"),
                Path("assets/how-it-works/layers-dark.svg"),
                Path("assets/how-it-works/journey-dark.svg"),
                Path("assets/how-it-works/database-dark.svg"),
                Path("assets/how-it-works/handover-dark.svg"),
            },
            outputs.keys(),
        )
        guide = outputs[Path("HOW_IT_WORKS.md")]
        self.assertIn("<!-- Generated by docs.how_it_works", guide)
        self.assertNotIn("Reviewed source revision", guide)
        self.assertIn("## What moves", guide)
        self.assertIn("## What each transition preserves", guide)
        self.assertIn("## Where responsibilities live", guide)
        self.assertIn("## Follow one change", guide)
        self.assertIn("## The durable memory underneath", guide)
        self.assertIn("## Carry the project into another tool", guide)
        self.assertIn("A canonical work brief is published before an item is activated or resumed", guide)
        self.assertIn("ready-review evidence can be published during dispatch preparation", guide)
        self.assertIn("Resume restores paused or blocked work", guide)
        self.assertIn("Reopen returns deferred work to intake", guide)
        self.assertIn("Continue is advisory", guide)
        self.assertIn("Checkpoint acceptance publishes the exact result and independent review", guide)
        self.assertIn("focused storage mutation", guide)
        self.assertNotIn("complete stored facts", guide)
        self.assertNotIn("does not currently publish them into this registry", guide)
        self.assertIn("any task may borrow the single coordination lease", guide)
        self.assertIn("A preparation claim keeps an item ready", guide)
        self.assertIn("activation consumes that claim atomically", guide)
        self.assertIn("An attempt lease records which task session", guide)
        self.assertNotIn("requirements, plans, designs, briefs, results, blockers", guide)
        self.assertEqual(5, guide.count("<picture>"))
        self.assertEqual(5, guide.count('media="(prefers-color-scheme: dark)"'))
        for slug in ("product", "layers", "journey", "database", "handover"):
            self.assertIn(f'srcset="assets/how-it-works/{slug}-dark.svg"', guide)
            self.assertIn(f'src="assets/how-it-works/{slug}.svg"', guide)

    def test_diagrams_use_the_approved_reading_surfaces(self) -> None:
        outputs = render.build_outputs(ROOT)

        for path, svg in outputs.items():
            if path.suffix != ".svg":
                continue
            with self.subTest(path=path):
                palette = NIGHT_PALETTE if path.stem.endswith("-dark") else DAY_PALETTE
                self.assertIn(f'fill="{palette.canvas}"', svg)
                self.assertIn(f'stroke="{palette.grid}"', svg)
                self.assertIn(f"stroke: {palette.connector}", svg)
                self.assertIn(f'fill="{palette.primary}"', svg)
                self.assertIn("<metadata>Generated by docs.how_it_works</metadata>", svg)
                self.assertNotIn("source revision", svg)
                self.assertIn('<pattern id="grid"', svg)
                self.assertNotIn("linearGradient", svg)
                self.assertNotIn("feDropShadow", svg)

        for slug in ("product", "layers", "journey", "database", "handover"):
            day = outputs[Path(f"assets/how-it-works/{slug}.svg")]
            night = outputs[Path(f"assets/how-it-works/{slug}-dark.svg")]
            with self.subTest(slug=slug):
                self.assertEqual(
                    re.sub(r"#[0-9a-fA-F]{3,6}\b", "#COLOR", day),
                    re.sub(r"#[0-9a-fA-F]{3,6}\b", "#COLOR", night),
                )

    def test_diagrams_expose_accessible_names_and_descriptions(self) -> None:
        outputs = render.build_outputs(ROOT)
        namespace = {"svg": "http://www.w3.org/2000/svg"}

        for path, svg in outputs.items():
            if path.suffix != ".svg":
                continue
            with self.subTest(path=path):
                root = ElementTree.fromstring(svg)
                labelled_by = root.attrib["aria-labelledby"].split()
                self.assertEqual("img", root.attrib["role"])
                self.assertEqual(2, len(labelled_by))
                title = root.find("svg:title", namespace)
                description = root.find("svg:desc", namespace)
                self.assertIsNotNone(title)
                self.assertIsNotNone(description)
                assert title is not None
                assert description is not None
                self.assertEqual([title.attrib["id"], description.attrib["id"]], labelled_by)
                self.assertTrue(title.text)
                self.assertTrue(description.text)

    def test_maintained_python_checks_include_the_generator(self) -> None:
        configuration = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))

        self.assertIn("docs/how_it_works", configuration["tool"]["ruff"]["src"])
        self.assertIn("docs/how_it_works", configuration["tool"]["pyrefly"]["project-includes"])

    def test_renderer_uses_the_complete_palette_input(self) -> None:
        palette = Palette(
            canvas="#000001",
            grid="#000002",
            frame="#000003",
            card="#000004",
            card_border="#000005",
            text="#000006",
            label="#000007",
            muted_text="#000008",
            guide="#000009",
            connector="#00000a",
            primary="#00000b",
            secondary="#00000c",
        )

        svg = render_svg(product.DIAGRAM, palette)

        for color in astuple(palette):
            self.assertIn(color, svg)

    def test_renderer_keeps_text_above_geometry_and_protects_canvas_labels(self) -> None:
        svg = render_svg(layers.DIAGRAM, NIGHT_PALETTE)
        root = ElementTree.fromstring(svg)
        text_started = False

        for child in root:
            tag = child.tag.rsplit("}", 1)[-1]
            if tag == "text":
                text_started = True
            elif tag in {"line", "path", "rect"}:
                self.assertFalse(text_started, f"{tag} is painted over text")

        canvas_text_roles = {"section-label", "section-subtitle", "connector-label", "note", "note-meta"}
        for text in root.findall("{http://www.w3.org/2000/svg}text"):
            classes = set(text.attrib.get("class", "").split())
            if classes & canvas_text_roles:
                self.assertIn("canvas-text", classes)

        self.assertIn(".canvas-text { paint-order: stroke fill;", svg)
        self.assertIn(">policy remains independent<", svg)
        self.assertIn(">of interfaces and storage<", svg)
        self.assertNotIn(">policy remains independent of interfaces and storage<", svg)

    def test_renderer_rejects_fragile_connector_geometry(self) -> None:
        boxes = (
            Box("source", "", "Source", (), (), 10, 10, 100, 60),
            Box("target", "", "Target", (), (), 160, 10, 100, 60),
        )
        unsafe_routes = (
            (Connector(((110, 10), (160, 10)), "source", "target"), "stable card port"),
            (Connector(((110, 40), (160, 60)), "source", "target"), "orthogonal"),
        )

        for connector, message in unsafe_routes:
            with self.subTest(message=message), self.assertRaisesRegex(ValueError, message):
                render_svg(
                    Diagram("unsafe", "Unsafe", "Unsafe route", 280, 100, (), (), (connector,), boxes),
                    DAY_PALETTE,
                )

    def test_renderer_reserves_card_text_and_connector_clearance(self) -> None:
        boxes = (
            Box("source", "", "Source", (), (), 10, 10, 100, 60),
            Box("obstacle", "", "Obstacle", (), (), 130, 10, 100, 60),
            Box("target", "", "Target", (), (), 250, 10, 100, 60),
        )

        with self.assertRaisesRegex(ValueError, "right margin"):
            render_svg(
                Diagram(
                    "crowded-text",
                    "Crowded text",
                    "Crowded text",
                    280,
                    100,
                    (),
                    (),
                    (),
                    (Box("crowded", "", "Overlong card heading", (), (), 10, 10, 100, 60),),
                ),
                DAY_PALETTE,
            )

        with self.assertRaisesRegex(ValueError, "right margin"):
            render_svg(
                Diagram(
                    "tight-text",
                    "Tight text",
                    "Tight text",
                    280,
                    100,
                    (),
                    (),
                    (),
                    (Box("tight", "", "Attached knowledge", (), (), 10, 10, 180, 60),),
                ),
                DAY_PALETTE,
            )

        with self.assertRaisesRegex(ValueError, "clearance from obstacle"):
            render_svg(
                Diagram(
                    "crowded-route",
                    "Crowded route",
                    "Crowded route",
                    370,
                    100,
                    (),
                    (),
                    (Connector(((110, 40), (250, 40)), "source", "target"),),
                    boxes,
                ),
                DAY_PALETTE,
            )

        near_boxes = (
            Box("source", "", "Source", (), (), 10, 0, 100, 60),
            Box("obstacle", "", "Obstacle", (), (), 130, 30, 100, 60),
            Box("target", "", "Target", (), (), 250, 0, 100, 60),
        )
        with self.assertRaisesRegex(ValueError, "clearance from obstacle"):
            render_svg(
                Diagram(
                    "grazing-route",
                    "Grazing route",
                    "Grazing route",
                    370,
                    100,
                    (),
                    (),
                    (Connector(((110, 20), (250, 20)), "source", "target"),),
                    near_boxes,
                ),
                DAY_PALETTE,
            )

    def test_diagram_connectors_state_real_relationships(self) -> None:
        product_edges = {(value.source, value.target) for value in product.DIAGRAM.connectors}
        self.assertNotIn(("attempt-paused", "attempt-blocked"), product_edges)
        self.assertIn(("attempt-active", "attempt-blocked"), product_edges)

        self.assertTrue(all(value.label for value in layers.DIAGRAM.connectors))

        journey_edges = {(value.source, value.target) for value in journey.DIAGRAM.connectors}
        self.assertIn(("transaction", "views"), journey_edges)
        self.assertIn(("views", "latest"), journey_edges)
        self.assertIn(("latest", "result"), journey_edges)
        self.assertNotIn(("views", "result"), journey_edges)
        self.assertNotIn(("transaction", "result"), journey_edges)

        database_edges = {(value.source, value.target) for value in database.DIAGRAM.connectors}
        self.assertIn(("work-items", "dependencies"), database_edges)
        self.assertNotIn(("item-artifacts", "artifact-refs"), database_edges)
        self.assertIn(("meta", "history"), database_edges)

        database_boxes = {value.key: value for value in database.DIAGRAM.boxes}
        self.assertEqual("Accepted artifacts", database_boxes["artifact-refs"].title)
        self.assertNotIn("item-artifacts", database_boxes)
        self.assertEqual("Shared authority", database_boxes["coordination"].title)

        handover_edges = {(value.source, value.target) for value in handover.DIAGRAM.connectors}
        self.assertEqual(
            {
                ("ledger", "materialize"),
                ("artifacts", "materialize"),
                ("materialize", "package"),
                ("package", "consumer"),
            },
            handover_edges,
        )

    def test_product_view_distinguishes_advisory_continue_from_review_acceptance(self) -> None:
        advisory = decision_models.action_semantics(decision_models.ActionKind.CONTINUE)
        review_acceptance = decision_models.action_semantics(decision_models.ActionKind.ACCEPT_REVIEW_AND_CONTINUE)
        self.assertEqual(decision_models.ActionEffect.ADVISORY, advisory.effect)
        self.assertEqual(decision_models.ActionLifecyclePrecondition.ACTIVE_ATTEMPT, advisory.lifecycle_precondition)
        self.assertEqual(decision_models.ActionEffect.MUTATING, review_acceptance.effect)
        self.assertEqual(
            decision_models.ActionLifecyclePrecondition.REVIEW_ATTEMPT,
            review_acceptance.lifecycle_precondition,
        )

        product_boxes = {value.key: value for value in product.DIAGRAM.boxes}
        self.assertEqual("Awaiting a decision", product_boxes["intake"].title)
        self.assertEqual(("return · accept + continue",), product_boxes["review"].meta)
        self.assertEqual(("accept + continue → active",), product_boxes["attempt-review"].details)

        outputs = render.build_outputs(ROOT)
        for path in (
            Path("assets/how-it-works/product.svg"),
            Path("assets/how-it-works/product-dark.svg"),
        ):
            with self.subTest(path=path):
                svg = outputs[path]
                self.assertIn(">return · accept + continue<", svg)
                self.assertIn(">accept + continue → active<", svg)
                self.assertNotIn(">return · continue<", svg)
                self.assertNotIn(">correction / continue → active<", svg)

    def test_write_and_stale_check_round_trip(self) -> None:
        outputs = render.build_outputs(ROOT)
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory)
            render.write_outputs(destination, outputs)
            self.assertEqual((), render.stale_outputs(destination, outputs))

            changed = destination / "HOW_IT_WORKS.md"
            changed.write_text("stale\n", encoding="utf-8")
            self.assertEqual((Path("HOW_IT_WORKS.md"),), render.stale_outputs(destination, outputs))

    def test_authority_edit_without_output_change_does_not_churn_assets(self) -> None:
        baseline = render.build_outputs(ROOT)
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / "repository"
            shutil.copytree(ROOT, destination, ignore=shutil.ignore_patterns(".git", ".venv", "__pycache__"))
            architecture = destination / "ARCHITECTURE.md"
            architecture.write_text(architecture.read_text(encoding="utf-8") + "\n", encoding="utf-8")

            self.assertEqual(baseline, render.build_outputs(destination))

    def test_semantic_seed_change_is_stale_until_outputs_are_regenerated(self) -> None:
        changed_diagram = replace(product.DIAGRAM, title="Changed visitor-facing title")
        with patch.object(product, "DIAGRAM", changed_diagram):
            stale = render.stale_outputs(ROOT, render.build_outputs(ROOT))

        self.assertEqual(
            {
                Path("assets/how-it-works/product.svg"),
                Path("assets/how-it-works/product-dark.svg"),
            },
            set(stale),
        )

    def test_committed_outputs_match_their_sources(self) -> None:
        outputs = render.build_outputs(ROOT)
        stale = render.stale_outputs(ROOT, outputs)

        self.assertEqual(
            (),
            stale,
            "regenerate and commit stale visitor-guide files with: uv run --locked python -m docs.how_it_works.render",
        )

    def test_public_and_agent_facing_prose_uses_the_product_name(self) -> None:
        prose_paths = {ROOT / name for name in ("README.md", "HOW_IT_WORKS.md", "ARCHITECTURE.md")}
        prose_paths.update(path for path in (ROOT / "docs").rglob("*.md") if path.name != "AGENTS.md")
        prose_paths.update((ROOT / "skills").rglob("*.md"))

        for path in sorted(prose_paths):
            with self.subTest(path=path.relative_to(ROOT)):
                prose = path.read_text(encoding="utf-8")
                retired_prose_name = r"\bChar" + r"lie\b"
                self.assertNotRegex(prose, retired_prose_name)


if __name__ == "__main__":
    unittest.main()
