from dataclasses import dataclass
from enum import Enum


class DecisionFailureCode(Enum):
    ACTION_NOT_AVAILABLE = "ACTION_NOT_AVAILABLE"
    ACTION_NOT_MUTATING = "ACTION_NOT_MUTATING"
    ATTEMPT_AUTHORITY_REQUIRED = "ATTEMPT_AUTHORITY_REQUIRED"
    ATTEMPT_LEASE_REQUIRED = "ATTEMPT_LEASE_REQUIRED"
    ATTEMPT_LEASE_EXPIRED = "ATTEMPT_LEASE_EXPIRED"
    ATTEMPT_NOT_FOUND = "ATTEMPT_NOT_FOUND"
    DEPENDENCY_NOT_SATISFIED = "DEPENDENCY_NOT_SATISFIED"
    COORDINATION_LEASE_BUSY = "COORDINATION_LEASE_BUSY"
    COORDINATION_LEASE_REQUIRED = "COORDINATION_LEASE_REQUIRED"
    HISTORY_RECORD_EXISTS = "HISTORY_RECORD_EXISTS"
    ITEM_ALREADY_EXISTS = "ITEM_ALREADY_EXISTS"
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    ITEM_SCOPE_INVALID = "ITEM_SCOPE_INVALID"
    ITEM_SCOPE_STALE = "ITEM_SCOPE_STALE"
    LIVE_DEPENDENTS = "LIVE_DEPENDENTS"
    LEASE_FENCED = "LEASE_FENCED"
    PROPOSAL_NOT_FOUND = "PROPOSAL_NOT_FOUND"
    PROPOSAL_ALREADY_EXISTS = "PROPOSAL_ALREADY_EXISTS"
    PROPOSAL_IDENTITY_INVALID = "PROPOSAL_IDENTITY_INVALID"
    PROPOSAL_INVALID = "PROPOSAL_INVALID"
    TRANSITION_INPUT_INVALID = "TRANSITION_INPUT_INVALID"


@dataclass(frozen=True, slots=True)
class DecisionFailure:
    code: DecisionFailureCode
    message: str


class HistoryRecordErrorCode(Enum):
    ARTIFACT_IDENTITY_DUPLICATE = "HISTORY_ARTIFACT_IDENTITY_DUPLICATE"
    ARTIFACT_KIND_ROLE_MISMATCH = "HISTORY_ARTIFACT_KIND_ROLE_MISMATCH"
    ARTIFACT_ORDER_INVALID = "HISTORY_ARTIFACT_ORDER_INVALID"
    ARTIFACT_ROLE_POSITIONS_INVALID = "HISTORY_ARTIFACT_ROLE_POSITIONS_INVALID"
    ARTIFACT_SELECTOR_INVALID = "HISTORY_ARTIFACT_SELECTOR_INVALID"
    DEPENDENCIES_INVALID = "HISTORY_DEPENDENCIES_INVALID"


class HistoryRecordError(ValueError):
    code: HistoryRecordErrorCode

    def __init__(self, code: HistoryRecordErrorCode, message: str) -> None:
        self.code = code
        super().__init__(f"{code.value}: {message}")
