from dataclasses import dataclass
from enum import Enum


class DecisionFailureCode(Enum):
    ACTION_NOT_AVAILABLE = "ACTION_NOT_AVAILABLE"
    ACTION_NOT_MUTATING = "ACTION_NOT_MUTATING"
    ATTEMPT_AUTHORITY_REQUIRED = "ATTEMPT_AUTHORITY_REQUIRED"
    ATTEMPT_LEASE_REQUIRED = "ATTEMPT_LEASE_REQUIRED"
    ATTEMPT_NOT_FOUND = "ATTEMPT_NOT_FOUND"
    DEPENDENCY_NOT_SATISFIED = "DEPENDENCY_NOT_SATISFIED"
    HISTORY_OUTCOME_INVALID = "HISTORY_OUTCOME_INVALID"
    HISTORY_RECORD_EXISTS = "HISTORY_RECORD_EXISTS"
    ITEM_ALREADY_EXISTS = "ITEM_ALREADY_EXISTS"
    ITEM_NOT_FOUND = "ITEM_NOT_FOUND"
    ITEM_SCOPE_INVALID = "ITEM_SCOPE_INVALID"
    ITEM_SCOPE_STALE = "ITEM_SCOPE_STALE"
    LIVE_DEPENDENTS = "LIVE_DEPENDENTS"
    PLANNING_ACTION_STALE = "PLANNING_ACTION_STALE"
    PLANNING_IMPACT_INVALID = "PLANNING_IMPACT_INVALID"
    PLANNING_IMPACT_UNRESOLVED = "PLANNING_IMPACT_UNRESOLVED"
    PLANNING_OBLIGATION_NOT_FOUND = "PLANNING_OBLIGATION_NOT_FOUND"
    PLANNING_RESOLUTION_INVALID = "PLANNING_RESOLUTION_INVALID"
    PROPOSAL_NOT_FOUND = "PROPOSAL_NOT_FOUND"
    RESOURCE_INSTANCE_REQUIRED = "RESOURCE_INSTANCE_REQUIRED"
    RESOURCE_INSTANCE_RESERVED = "RESOURCE_INSTANCE_RESERVED"
    RESOURCE_REQUIREMENT_INVALID = "RESOURCE_REQUIREMENT_INVALID"
    RESOURCE_RESERVATION_STALE = "RESOURCE_RESERVATION_STALE"
    RESOURCE_USE_LEASE_STALE = "RESOURCE_USE_LEASE_STALE"
    TRANSITION_INPUT_INVALID = "TRANSITION_INPUT_INVALID"


@dataclass(frozen=True, slots=True)
class DecisionFailure:
    code: DecisionFailureCode
    message: str
