import argparse
import hashlib
from collections.abc import Mapping, Sequence
from pathlib import Path

from . import database, journey, layers, product
from .model import Diagram, render_svg

OUTPUT_PATHS = {
    "guide": Path("HOW_IT_WORKS.md"),
    "product": Path("assets/how-it-works/product.svg"),
    "layers": Path("assets/how-it-works/layers.svg"),
    "journey": Path("assets/how-it-works/journey.svg"),
    "database": Path("assets/how-it-works/database.svg"),
}

WATCHED_AUTHORITIES = (
    Path("ARCHITECTURE.md"),
    Path("docs/how_it_works/VISUAL_LANGUAGE.md"),
    Path("src/pinboard/domain/work_models.py"),
    Path("src/pinboard/domain/decision_models.py"),
    Path("src/pinboard/domain/decisions.py"),
    Path("src/pinboard/application/service.py"),
    Path("src/pinboard/application/mutations.py"),
    Path("src/pinboard/adapters/sqlite/schema.sql"),
    Path("src/pinboard/adapters/sqlite/store.py"),
)


def _source_revision(root: Path) -> str:
    digest = hashlib.sha256()
    for relative_path in WATCHED_AUTHORITIES:
        digest.update(relative_path.as_posix().encode())
        digest.update(b"\0")
        digest.update(root.joinpath(relative_path).read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()[:16]


def _guide(source_revision: str) -> str:
    return f"""<!-- Generated by docs.how_it_works from executable seeds. Do not edit this file directly. -->
<!-- Reviewed source revision: {source_revision} -->

# How Pinboard works

Pinboard keeps repository work coherent across tasks and interruptions. It preserves what the project decided, which execution is acting on it, who may change it now, and what evidence another task can trust later.

The four views move from the visible workflow to package responsibilities, then follow one change and show the durable relationships underneath.

## What moves

A work item is the durable project decision. An attempt is one execution of that work. They move together while remaining separate: an item can survive interruption, correction, or a replacement worker without losing its identity or accepted scope.

![A work item lifecycle above the legal branches of an active attempt, with related facts shown separately](assets/how-it-works/product.svg)

The primary path is intentionally familiar: intake becomes ready, active work enters review, and accepted work becomes a terminal outcome. Deferred, paused, and blocked work are optional branches rather than required stages. Paused and blocked work can resume the same attempt; review can request correction, pause at an accepted checkpoint, continue the attempt, or complete it. Completion can also be accepted directly from active work.

Proposals and dependencies are not extra states. Accepted scope is the exact authorized revision an attempt uses. Mutation ownership records who may act now: either one graph-wide coordination holder or one attempt lease. A review candidate identifies the exact result under review, and evidence supports its acceptance.

## What each transition preserves

The lifecycle is accompanied by four guarantees:

- **Work survives conversations.** A later task can continue from accepted scope and evidence instead of reconstructing intent from chat history.
- **Mutation ownership is current.** An expired or replaced worker cannot apply an action it discovered earlier.
- **Review is about one candidate.** Correction, checkpoint acceptance, continuation, and terminal completion preserve different outcomes without changing which work they belong to.
- **Transitions are atomic.** An accepted change updates its related facts and history together; a rejected or failed change leaves the previous ledger intact.

These guarantees explain why seemingly similar words remain distinct.

## Where responsibilities live

The package is split into four layers because each removes a different kind of ambiguity. The split keeps workflow policy out of storage and keeps external representations out of decisions.

![Four package layers showing interfaces, application, domain, and adapters, connected by package dependencies](assets/how-it-works/layers.svg)

Every arrow in this view means “may depend on”; the next view shows runtime flow. Interfaces absorb the variability of command lines, JSON, project files, and human-readable output. Application code coordinates complete operations against current state. The domain decides legality as pure data. Adapters make accepted facts durable and recoverable. These transformations prevent one layer from silently interpreting facts owned by another.

## Follow one change

Submitting work for review is one visible action, but it strengthens meaning at every boundary. External values become an exact command. The application reloads current state and mutation ownership inside the write operation. Domain evaluation returns either an accepted change or an expected rejection; rejection leaves the ledger unchanged. The application projects an accepted change into complete stored facts, and SQLite either commits all of them with a history receipt or commits nothing.

![A submit-review request travelling through interface decoding, application orchestration, domain decision, mutation projection, and atomic SQLite commit](assets/how-it-works/journey.svg)

The layers do not repeat the same decision. Each contributes a different guarantee, then hands a narrower value to the next owner. Generated views refresh after the authoritative commit and can be rebuilt from the ledger if that refresh is interrupted.

## The durable memory underneath

The relational ledger groups sixteen tables into six kinds of memory: current work, accepted scope and dependencies, discoveries, immutable knowledge, changing mutation ownership, and the history that connects them.

![Six groups of SQLite tables showing current work, scope, discovery, durable knowledge, mutation ownership, and history](assets/how-it-works/database.svg)

A work item survives attempts. Accepted versions preserve current scope and its revision history. Proposal evidence records why possible work was raised, while its freshness assumptions record which facts must be checked again.

Pinboard currently publishes two kinds of immutable artifact. A canonical work brief is published before an item is activated or resumed. The attempt selects that brief, and dispatch later resolves its accepted reference and verifies the exact bytes. Independent ready-review evidence can be published during dispatch preparation and linked to the work item, allowing the same review to be verified and reused.

The database can represent additional artifact kinds and relationships, but those storage shapes are not active publication paths. Attempt-local result, review, and blocker files support delivery and review; the installed application does not currently publish them into this registry.

Mutation ownership has two scopes. Shared-change authority is temporary: any task may borrow the single coordination lease for one shared scheduling or graph-wide change, then release it. It is not a coordinator task and does not create or message other tasks. Its exclusivity prevents a conflicting shared decision during that operation and authorizes replacement or revocation of an attempt owner. An attempt lease records which task session—identified by task, host, and lease id—owns one implementation attempt. Its generation fences an older owner after transfer or revocation, while leases for unrelated attempts remain independent. Project state holds the current revision, and committed history records each accepted input, outcome, and actor.

For installation and the product story, return to the [README](README.md). For contributor-facing ownership, storage boundaries, and representative command flows, continue to the [architecture map](ARCHITECTURE.md).

---

<sub>This guide and its SVG diagrams are generated from the executable seeds in <code>docs/how_it_works/</code>. The repository check requires their committed outputs to match current workflow, architecture, journey, and schema authorities.</sub>
"""


def _output_path(item: tuple[Path, str]) -> str:
    return item[0].as_posix()


def build_outputs(root: Path) -> dict[Path, str]:
    product.validate()
    layers.validate(root)
    journey.validate()
    database.validate(root)
    source_revision = _source_revision(root)
    diagrams: tuple[Diagram, ...] = (product.DIAGRAM, layers.DIAGRAM, journey.DIAGRAM, database.DIAGRAM)
    outputs = {OUTPUT_PATHS[diagram.slug]: render_svg(diagram, source_revision) for diagram in diagrams}
    outputs[OUTPUT_PATHS["guide"]] = _guide(source_revision)
    return dict(sorted(outputs.items(), key=_output_path))


def stale_outputs(root: Path, outputs: Mapping[Path, str]) -> tuple[Path, ...]:
    stale: list[Path] = []
    for relative_path, expected in outputs.items():
        path = root / relative_path
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(relative_path)
    return tuple(stale)


def write_outputs(root: Path, outputs: Mapping[Path, str]) -> None:
    for relative_path, content in outputs.items():
        path = root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main(arguments: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the visitor-facing How Pinboard works guide.")
    parser.add_argument("--check", action="store_true", help="fail when committed outputs are stale")
    options = parser.parse_args(arguments)
    root = Path(__file__).resolve().parents[2]
    outputs = build_outputs(root)
    if options.check:
        stale = stale_outputs(root, outputs)
        if stale:
            print("generated visitor guide is stale:")
            for path in stale:
                print(f"  {path}")
            print("run: uv run --locked python -m docs.how_it_works.render")
            return 1
        print("generated visitor guide is current")
        return 0
    write_outputs(root, outputs)
    print(f"generated {len(outputs)} visitor-guide files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
