import argparse
import hashlib
from collections.abc import Mapping, Sequence
from pathlib import Path

from . import database, journey, layers, product
from .model import Diagram, render_svg

OUTPUT_PATHS = {
    "guide": Path("HOW_IT_WORKS.md"),
    "product": Path("assets/how-it-works/product.svg"),
    "layers": Path("assets/how-it-works/layers.svg"),
    "journey": Path("assets/how-it-works/journey.svg"),
    "database": Path("assets/how-it-works/database.svg"),
}

WATCHED_AUTHORITIES = (
    Path("ARCHITECTURE.md"),
    Path("docs/how_it_works/VISUAL_LANGUAGE.md"),
    Path("src/charlie_pinboard/domain/work_models.py"),
    Path("src/charlie_pinboard/domain/decision_models.py"),
    Path("src/charlie_pinboard/domain/decisions.py"),
    Path("src/charlie_pinboard/application/service.py"),
    Path("src/charlie_pinboard/application/mutations.py"),
    Path("src/charlie_pinboard/adapters/sqlite/schema.sql"),
    Path("src/charlie_pinboard/adapters/sqlite/store.py"),
)


def _source_revision(root: Path) -> str:
    digest = hashlib.sha256()
    for relative_path in WATCHED_AUTHORITIES:
        digest.update(relative_path.as_posix().encode())
        digest.update(b"\0")
        digest.update(root.joinpath(relative_path).read_bytes())
        digest.update(b"\0")
    return digest.hexdigest()[:16]


def _guide(source_revision: str) -> str:
    return f"""<!-- Generated by docs.how_it_works from executable seeds. Do not edit this file directly. -->
<!-- Reviewed source revision: {source_revision} -->

# How Pinboard works

Pinboard looks like a small workflow engine: work appears, moves, pauses, resumes, and eventually leaves the live queue. The consequential part is not moving a label from one column to another. Pinboard preserves what the project decided, which execution is acting on it, who may change it now, and what evidence another task can trust later.

This guide shows the same system from four perspectives. Each view omits detail deliberately; together they explain why the implementation is larger than its basic state diagram suggests.

## What moves

A work item is the durable project decision. An attempt is one execution of that work. They move together while remaining separate: an item can survive interruption, correction, or a replacement worker without losing its identity or accepted scope.

![A work item lifecycle above a parallel attempt lifecycle, with proposal, scope, authority, and evidence travelling alongside them](assets/how-it-works/product.svg)

The primary path is intentionally familiar: intake becomes ready, active work enters review, and accepted work becomes a terminal outcome. The side paths carry the distinctions that matter later. Deferred work was consciously saved. Paused work can continue without inventing a blocker. Blocked work retains a named condition. Review protects one exact candidate.

Proposals, dependencies, accepted scope, authority, and evidence are not extra states. They answer different questions about the same work, so squeezing them into one status would make the workflow smaller on paper and less truthful in use.

## Why the code has consequences

Four promises turn the simple-looking lifecycle into durable coordination:

- **Work survives conversations.** A later task can continue from accepted scope and evidence instead of reconstructing intent from chat history.
- **Authority is current.** An expired or replaced worker cannot apply an action it discovered earlier.
- **Review is about one candidate.** Correction, checkpoint acceptance, continuation, and terminal completion preserve different outcomes without changing which work they belong to.
- **Transitions are atomic.** An accepted change updates its related facts and history together; a rejected or failed change leaves the previous ledger intact.

These promises explain why seemingly similar words remain distinct. They also explain why boundaries and exact representations occupy more code than the state names themselves.

## Where responsibilities live

The package is split into four layers because each removes a different kind of ambiguity. The split keeps workflow policy out of storage and keeps external representations out of decisions.

![Four package layers showing interfaces, application, domain, and adapters with the question each layer answers](assets/how-it-works/layers.svg)

Interfaces absorb the variability of command lines, JSON, project files, and human-readable output. Application code coordinates complete operations against current state. The domain decides legality as pure data. Adapters make accepted facts durable and recoverable. Most of the implementation exists at those transformations, where silent interpretation would otherwise accumulate.

## Follow one change

Submitting work for review is one visible action, but it strengthens meaning at every boundary. External values become an exact command. The application reloads current state and authority inside the write operation. The domain returns one closed review change. The application projects that decision into complete stored facts, and SQLite either commits all of them with a history receipt or commits nothing.

![A submit-review request travelling through interface decoding, application orchestration, domain decision, mutation projection, and atomic SQLite commit](assets/how-it-works/journey.svg)

The layers do not repeat the same decision. Each contributes a different guarantee, then hands a narrower value to the next owner.

## The durable memory underneath

The relational ledger is intentionally the busiest view. Sixteen tables are not sixteen workflow states. They preserve six different kinds of memory: current work, accepted scope and dependencies, discoveries, immutable knowledge, changing authority, and the history that connects them.

![Six groups of SQLite tables showing current work, scope, discovery, durable knowledge, authority, and history](assets/how-it-works/database.svg)

A work item survives attempts. Scope survives edits. Evidence survives conversations. Authority changes over time. The database makes those relationships explicit so the application does not have to infer them from filenames, Markdown, or whichever task happens to be open.

This is still one local workflow engine. Its size comes from making the consequential parts explicit: meaning at the boundary, legality at the center, and durable relationships underneath.

For installation and the product story, return to the [README](README.md). For contributor-facing ownership, storage boundaries, and representative command flows, continue to the [architecture map](ARCHITECTURE.md).

---

<sub>This guide and its SVG diagrams are generated from the executable seeds in <code>docs/how_it_works/</code>. The repository check requires their committed outputs to match current workflow, architecture, journey, and schema authorities.</sub>
"""


def _output_path(item: tuple[Path, str]) -> str:
    return item[0].as_posix()


def build_outputs(root: Path) -> dict[Path, str]:
    product.validate()
    layers.validate(root)
    journey.validate()
    database.validate(root)
    source_revision = _source_revision(root)
    diagrams: tuple[Diagram, ...] = (product.DIAGRAM, layers.DIAGRAM, journey.DIAGRAM, database.DIAGRAM)
    outputs = {OUTPUT_PATHS[diagram.slug]: render_svg(diagram, source_revision) for diagram in diagrams}
    outputs[OUTPUT_PATHS["guide"]] = _guide(source_revision)
    return dict(sorted(outputs.items(), key=_output_path))


def stale_outputs(root: Path, outputs: Mapping[Path, str]) -> tuple[Path, ...]:
    stale: list[Path] = []
    for relative_path, expected in outputs.items():
        path = root / relative_path
        if not path.is_file() or path.read_text(encoding="utf-8") != expected:
            stale.append(relative_path)
    return tuple(stale)


def write_outputs(root: Path, outputs: Mapping[Path, str]) -> None:
    for relative_path, content in outputs.items():
        path = root / relative_path
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main(arguments: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the visitor-facing How Pinboard works guide.")
    parser.add_argument("--check", action="store_true", help="fail when committed outputs are stale")
    options = parser.parse_args(arguments)
    root = Path(__file__).resolve().parents[2]
    outputs = build_outputs(root)
    if options.check:
        stale = stale_outputs(root, outputs)
        if stale:
            print("generated visitor guide is stale:")
            for path in stale:
                print(f"  {path}")
            print("run: uv run --locked python -m docs.how_it_works.render")
            return 1
        print("generated visitor guide is current")
        return 0
    write_outputs(root, outputs)
    print(f"generated {len(outputs)} visitor-guide files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
